### ISSUE TITLE
Password Set/Reset Page

### ISSUE THREAD

**Issue by karthikeya-io** [karthikeya-io/wadla#1]
## Feature: Password Reset Page

**Description:**
A registered user should able to set/reset my password. This feature will provide an easy and secure way to gain/regain access to my account.

**Tasks:**
- [ ] Design and implement the password reset page UI.
- [ ] Create UI elements for users to enter their email address, OTP (One-Time Password), new password, and confirm new password.
- [ ] Implement the frontend logic to handle user interactions and input validation.

**Additional Information:**
- The password reset process starts with the user providing their registered email address.
- Upon submitting the email address, a POST request will be sent to the backend to initiate the password reset process.
- Once the backend validates the email address, the user will be prompted to enter the OTP they receive.
- OTP and new password will be sent in one POST request.

**Related issues**
#2

**Comment by charan1409** [comment]
I will work on this issue
